import { Separator } from "@/components/ui/separator";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col ">
      <div className="h-32 w-full grid place-items-center">
        <h1 className="text-3xl font-semibold">Online Voting System</h1>
      </div>
      <Separator className="bg-slate-500" />
      {children}
    </div>
  );
}
