import React from "react";
import SignupForm from "../_components/register-form";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Register",
  description: "Generated by create next app",
};

interface pageProps {}

const page: React.FC<pageProps> = ({}) => {
  return (
    <div className="flex flex-col items-center justify-center my-20 gap-4">
      <h1 className="font-semibold text-2xl">Register</h1>
      <SignupForm />
      <div className="flex gap-1 text-sm">
        <span>Alread a user? </span>
        <Link href="/login" className="text-blue-900">
          Login here
        </Link>
      </div>
    </div>
  );
};

export default page;
